(function() {

  var Forecast = require('../node_modules/forecast.io');
  var weather_module = require('./Weather_class');
  

  function CurrentWeather(){

    var isSimulated = true;
    var forecast;

    if(process.env.FORECAST_KEY){
      var options = { APIKey: process.env.FORECAST_KEY };
      forecast = new Forecast(options);
      isSimulated = false;
    }


    this.getCurrentWeatherConditions_byLatitudeLongitude = function(latitude, longitude, callback){
      
      var current_weather_condition = new weather_module.Weather(latitude, longitude, 'Celsius', null);

      if(isSimulated){
        current_weather_condition.read();
        console.log("Current Weather Generated by Simulation!");
        callback(current_weather_condition.get());
      }
      else{
        //invoke the real weather API
        forecast.get(latitude, longitude, function (err, res, data) {
          if (err) throw err;

          console.log("Current Weather Received by API!");
          //I got "data" that is a huge JSON. I need only some fileds. Therefore I filter it
          //in order to create a new Weather() with only the field that I really use.
          current_weather_condition.setPrecipProbability(data.currently.precipProbability);
          current_weather_condition.setTemperature(data.currently.temperature);
          current_weather_condition.setHumidity(data.currently.humidity);
          current_weather_condition.setWindSpeed(data.currently.windSpeed);
          current_weather_condition.setLightIntensitiy(current_weather_condition.convertIntoNumericalLightIntensity(data.currently.icon));
          callback(current_weather_condition.get());
        });
      }
    }

    this.getCurrentWeatherConditions_byCityName = function(city, callback){
      //todo - not now
      return -1;
    }
  }


  exports.CurrentWeather = CurrentWeather;

})();