(function() {

  var Forecast = require('../node_modules/forecast.io');
  var weather_module = require('./Weather_class');


  function DailyForecastWeather(){

    var isSimulated = true;
    var forecast;

    if(process.env.FORECAST_KEY){
      var options = { APIKey: process.env.FORECAST_KEY };
      forecast = new Forecast(options);
      isSimulated = false;
    }

    var dailyForecastWeather = []; // contains an array of ForecastWeather for each day of the next week


    this.getDailyForcastWeatherConditions_byLatitudeLongitude = function(latitude, longitude, numberDays, callback){
      if(isSimulated){
        //generate a list of forecast weather days (1 week)
        currentDay = new Date();
        for(var i=0; i<numberDays; i++){
          var newDay = generateDateNextDay(currentDay);
          var tmp_forecastWeather = new weather_module.Weather(latitude, longitude, 'Celsius', newDay);
          tmp_forecastWeather.read();
          dailyForecastWeather.push(tmp_forecastWeather.get());
          currentDay = newDay;
        }
        console.log("Daily Forecast Generated by Simulation!");
        callback(dailyForecastWeather);
      }
      else{
        //invoke the real weather API
        forecast.get(latitude, longitude, function (err, res, data) {
          if (err) throw err;
          console.log("Daily Forecast Weather Received by API!");
          
          daily_forecast = data.daily.data;
          for(var i=1; i<numberDays; i++){
            var tmp_forecastWeather = new weather_module.Weather(latitude, longitude, 'Celsius', new Date(daily_forecast[i].time*1000));
            tmp_forecastWeather.setPrecipProbability(daily_forecast[i].precipProbability);
            var average_temperature = (daily_forecast[i].temperatureMax + daily_forecast[i].temperatureMin)/2;
            tmp_forecastWeather.setTemperature(average_temperature);
            tmp_forecastWeather.setHumidity(daily_forecast[i].humidity);
            tmp_forecastWeather.setWindSpeed(daily_forecast[i].windSpeed);
            tmp_forecastWeather.setLightIntensitiy(tmp_forecastWeather.convertIntoNumericalLightIntensity(daily_forecast[i].icon));
            dailyForecastWeather.push(tmp_forecastWeather.get());
          }
          callback(dailyForecastWeather);
        });
      }
    }

    this.getDailyForcastWeatherConditions_byCityName = function(city, callback){
      //todo - not now
      return -1;
    }

  }//end class WeeklyForecastWeatherData


  var generateDateNextDay = function(currentDate){
    var currentMonth = currentDate.getMonth();
    var currentYear = currentDate.getFullYear();
    var currentDay = currentDate.getDate();

    if(currentDay==31 & currentMonth==11){
      var newDay = 1;
      var newMonth = 0; //gen
      var newYear = currentYear + 1;
    }
    else if(daysInMonth((currentMonth+1),currentYear) == currentDay){
      //es: currentMonth = 28 & currentDay = 28 => go to the next month!
      var newDay = 1;
      var newMonth = currentMonth + 1;
      var newYear = currentYear; //non è detto... se sono l'ultimo dell'anno non vale
    }
    else{
      var newDay = currentDay + 1;
      var newMonth = currentMonth;
      var newYear = currentYear;
    }

    return new Date(newYear, newMonth, newDay);
  }


  //Get Number of Days in one Month
  function daysInMonth(month,year) {
    return new Date(year, month, 0).getDate();
  }


  exports.DailyForecastWeather = DailyForecastWeather;

})();